import Foundation
import Combine
import CoreBluetooth

/// Reads **live heart rate directly off the Oura ring over BLE** — no cloud API.
///
/// ⚠️ This talks the ring's **proprietary, encrypted, undocumented** protocol,
/// reconstructed from the community `open_oura` reverse-engineering project. It is
/// **against Oura's Terms of Service**, can break on any firmware update, and needs
/// **your ring's 16-byte auth key** (generated by the official Oura app and stored
/// in its local database — you must extract it and paste it into Connect). Because
/// it can't be validated without the hardware, treat frame offsets marked "best
/// effort" as tunable if your ring/firmware differs.
///
/// Flow:  scan for the ring service → connect → discover write/notify chars →
/// enable notifications → GetAuthNonce → AES-ECB-encrypt the nonce with your key →
/// Authenticate → start the real-time PPG stream → decode inter-beat intervals
/// (IBI) into BPM.
final class OuraRingHeartRateSource: NSObject, HeartRateSource {
    let kind: HeartRateSourceKind = .ouraRing

    static let keychainKey = "oura.ring.auth.key"

    // Reverse-engineered GATT layout (Ring Gen 3/4/5 share it).
    private let ringServiceUUID = CBUUID(string: "98ED0001-A541-11E4-B6A0-0002A5D5C51B")
    private let writeCharUUID   = CBUUID(string: "98ED0002-A541-11E4-B6A0-0002A5D5C51B")
    private let notifyCharUUID  = CBUUID(string: "98ED0003-A541-11E4-B6A0-0002A5D5C51B")

    // Protocol frames.
    private let getAuthNonceFrame = Data([0x2f, 0x01, 0x2b])
    private let startStreamFrame  = Data([0x06, 0x07, 0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00]) // PPG on-demand, 1 min
    private let stopStreamFrame   = Data([0x06, 0x04, 0x00, 0x00, 0x00, 0x00])

    private let authKey: Data?      // 16 bytes
    private let sampleSubject = PassthroughSubject<HeartRateSample, Never>()
    private let stateSubject  = CurrentValueSubject<HeartRateConnectionState, Never>(.disconnected)

    private var central: CBCentralManager?
    private var peripheral: CBPeripheral?
    private var writeChar: CBCharacteristic?
    private var wantsToRun = false
    private var authenticated = false
    private var keepAlive: Timer?

    /// Exponential moving average of BPM to smooth beat-to-beat jitter.
    private var smoothedBPM: Double?

    init(authKey: Data?) {
        self.authKey = authKey
        super.init()
    }

    var samples: AnyPublisher<HeartRateSample, Never> { sampleSubject.eraseToAnyPublisher() }
    var state: AnyPublisher<HeartRateConnectionState, Never> { stateSubject.eraseToAnyPublisher() }

    func start() {
        guard authKey?.count == 16 else {
            stateSubject.send(.unavailable(reason: "Add your Oura ring key in Connect"))
            return
        }
        wantsToRun = true
        if central == nil {
            central = CBCentralManager(delegate: self, queue: nil)
        } else {
            beginScanIfPossible()
        }
    }

    func stop() {
        wantsToRun = false
        authenticated = false
        keepAlive?.invalidate()
        keepAlive = nil
        if let peripheral, let writeChar {
            peripheral.writeValue(stopStreamFrame, for: writeChar, type: .withResponse)
        }
        central?.stopScan()
        if let peripheral { central?.cancelPeripheralConnection(peripheral) }
        peripheral = nil
        writeChar = nil
        smoothedBPM = nil
        stateSubject.send(.disconnected)
    }

    private func beginScanIfPossible() {
        guard wantsToRun, let central, central.state == .poweredOn else { return }
        stateSubject.send(.connecting)
        central.scanForPeripherals(withServices: [ringServiceUUID], options: nil)
    }

    private func send(_ frame: Data) {
        guard let peripheral, let writeChar else { return }
        peripheral.writeValue(frame, for: writeChar, type: .withResponse)
    }

    // MARK: - Auth

    private func requestNonce() {
        stateSubject.send(.connecting)
        send(getAuthNonceFrame)
    }

    private func handleNonce(_ nonce: Data) {
        guard let authKey, let encrypted = AESECB.encrypt(nonce, key: authKey) else {
            stateSubject.send(.unavailable(reason: "Ring auth failed (bad key?)"))
            return
        }
        // Authenticate: 0x2f 0x11 0x2d + 16 encrypted bytes.
        var frame = Data([0x2f, 0x11, 0x2d])
        frame.append(encrypted.prefix(16))
        send(frame)
    }

    private func handleAuthResult(success: Bool) {
        guard success else {
            stateSubject.send(.unavailable(reason: "Ring rejected the key"))
            return
        }
        authenticated = true
        stateSubject.send(.connected(deviceName: peripheral?.name ?? "Oura Ring"))
        startStreaming()
    }

    private func startStreaming() {
        send(startStreamFrame)
        // The ring caps a stream request at ~1 minute, so re-arm it periodically.
        keepAlive?.invalidate()
        let timer = Timer(timeInterval: 50, repeats: true) { [weak self] _ in
            guard let self, self.authenticated else { return }
            self.send(self.startStreamFrame)
        }
        RunLoop.main.add(timer, forMode: .common)
        keepAlive = timer
    }

    // MARK: - Notification parsing

    /// A notification value may contain one or more TLV frames: [tag, length, payload…].
    private func parse(_ value: Data) {
        let bytes = [UInt8](value)
        var offset = 0
        while offset + 2 <= bytes.count {
            let tag = bytes[offset]
            let length = Int(bytes[offset + 1])
            let payloadStart = offset + 2
            let payloadEnd = min(payloadStart + length, bytes.count)
            guard payloadStart <= payloadEnd else { break }
            let payload = Array(bytes[payloadStart..<payloadEnd])
            handleFrame(tag: tag, payload: payload)
            if length == 0 { break }
            offset = payloadEnd
        }
    }

    private func handleFrame(tag: UInt8, payload: [UInt8]) {
        switch tag {
        case 0x2f: // extended / auth responses; payload[0] is the extended tag
            guard let ext = payload.first else { return }
            switch ext {
            case 0x2c: // GetAuthNonce response → 15-byte nonce follows the ext tag
                let nonce = Array(payload.dropFirst().prefix(15))
                if nonce.count == 15 { handleNonce(Data(nonce)) }
            case 0x2e: // Authenticate response → result byte follows the ext tag
                let result = payload.count > 1 ? payload[1] : 0xFF
                handleAuthResult(success: result == 0x00)
            default:
                break
            }

        case 0x80: // green_ibi_quality_event: ibi = (b0 << 3) | (b1 & 0x07)
            guard payload.count >= 2 else { return }
            let ibiMs = (Int(payload[0]) << 3) | (Int(payload[1]) & 0x07)
            emit(fromIBI: ibiMs)

        case 0x60: // ibi_and_amplitude_event: 6× IBI (16-bit LE) + amplitude — best effort
            var i = 0
            while i + 1 < payload.count && i < 12 {
                let ibiMs = Int(payload[i]) | (Int(payload[i + 1]) << 8)
                emit(fromIBI: ibiMs)
                i += 2
            }

        default:
            break
        }
    }

    /// Convert an inter-beat interval (ms) into a smoothed BPM sample, gating
    /// physiologically implausible values (≈40–240 bpm).
    private func emit(fromIBI ibiMs: Int) {
        guard ibiMs >= 250, ibiMs <= 1500 else { return }
        let instantaneous = 60_000.0 / Double(ibiMs)
        let smoothed = smoothedBPM.map { $0 * 0.7 + instantaneous * 0.3 } ?? instantaneous
        smoothedBPM = smoothed
        sampleSubject.send(HeartRateSample(bpm: Int(smoothed.rounded()), timestamp: Date(), origin: .ouraRing))
    }
}

// MARK: - CBCentralManagerDelegate

extension OuraRingHeartRateSource: CBCentralManagerDelegate {
    func centralManagerDidUpdateState(_ central: CBCentralManager) {
        switch central.state {
        case .poweredOn: beginScanIfPossible()
        case .poweredOff: stateSubject.send(.unavailable(reason: "Bluetooth is off"))
        case .unauthorized: stateSubject.send(.unavailable(reason: "Bluetooth permission denied"))
        case .unsupported: stateSubject.send(.unavailable(reason: "Bluetooth LE not supported"))
        default: break
        }
    }

    func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral,
                        advertisementData: [String: Any], rssi RSSI: NSNumber) {
        central.stopScan()
        self.peripheral = peripheral
        peripheral.delegate = self
        central.connect(peripheral, options: nil)
    }

    func centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral) {
        peripheral.discoverServices([ringServiceUUID])
    }

    func centralManager(_ central: CBCentralManager, didDisconnectPeripheral peripheral: CBPeripheral, error: Error?) {
        authenticated = false
        keepAlive?.invalidate(); keepAlive = nil
        stateSubject.send(.disconnected)
        if wantsToRun { beginScanIfPossible() }
    }

    func centralManager(_ central: CBCentralManager, didFailToConnect peripheral: CBPeripheral, error: Error?) {
        stateSubject.send(.disconnected)
        if wantsToRun { beginScanIfPossible() }
    }
}

// MARK: - CBPeripheralDelegate

extension OuraRingHeartRateSource: CBPeripheralDelegate {
    func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        guard let service = peripheral.services?.first(where: { $0.uuid == ringServiceUUID }) else { return }
        peripheral.discoverCharacteristics([writeCharUUID, notifyCharUUID], for: service)
    }

    func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
        for characteristic in service.characteristics ?? [] {
            if characteristic.uuid == writeCharUUID {
                writeChar = characteristic
            } else if characteristic.uuid == notifyCharUUID {
                peripheral.setNotifyValue(true, for: characteristic)
            }
        }
        // Kick off auth once both the notify subscription and write handle are ready.
        if writeChar != nil { requestNonce() }
    }

    func peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?) {
        guard characteristic.uuid == notifyCharUUID, let value = characteristic.value else { return }
        parse(value)
    }
}
